ServerEvents.recipes((event) => {
  const removedTypes = [];

  const removedIDs = [
    'pneumaticcraft:huge_tank',
    'pneumaticcraft:thermopneumatic_processing_plant',
    'create_enchantment_industry:mixing/hyper_experience',
    'industrialforegoing:dissolution_chamber',
    'pneumaticcraft:small_tank',
    'pneumaticcraft:medium_tank',
    'pneumaticcraft:large_tank',
    'biomancy:crafting/primordial_core',
    'embers:mixing/molten_brass',
    'embers:mixing/molten_dawnstone',
    'minecraft:netherite_ingot',
    'orbital_railgun:orbital_railgun',
    "actuallyadditions:atomic_reconstructor",
    "actuallyadditions:basic_coil",
    "actuallyadditions:coal_generator",
    "actuallyadditions:energizer",
    "actuallyadditions:fermenting/refined_canola",
    "actuallyadditions:pressing/canola",
    "apotheosis:reforging_table",
    "create_central_kitchen:crafting/cooking_guide",
    "create:crafting/kinetics/brass_hand",
    "create:crafting/kinetics/controls",
    "create:crafting/kinetics/fluid_tank",
    "create:crafting/kinetics/schedule",
    "create:crafting/materials/andesite_alloy_from_zinc",
    "create:crafting/materials/andesite_alloy",
    "create:crushing/ochrum_recycling",
    "create:crushing/ochrum",
    "create:crushing/veridium_recycling",
    "create:crushing/veridium",
    "create:item_application/railway_casing",
    "create:mixing/andesite_alloy_from_zinc",
    "create:mixing/andesite_alloy",
    "create:mixing/brass_ingot",
    "create:splashing/gravel",
    "create:splashing/soul_sand",
    "createbigcannons:melting/melt_cast_iron_ingot",
    "curvy_pipes:energy_base",
    "curvy_pipes:fluid_base",
    "curvy_pipes:item_base",
    "immersive_aircraft:boiler",
    "immersive_aircraft:eco_engine",
    "immersive_aircraft:engine",
    "immersive_aircraft:enhanced_propeller",
    "immersive_aircraft:hull_reinforcement",
    "immersive_aircraft:hull",
    "immersive_aircraft:improved_landing_gear",
    "immersive_aircraft:industrial_gears",
    "immersive_aircraft:nether_engine",
    "immersive_aircraft:propeller",
    "immersive_aircraft:steel_boiler",
    "industrialforegoing:dissolution_chamber/infinity_backpack",
    "industrialforegoing:dissolution_chamber/infinity_nuke",
    "industrialforegoing:dissolution_chamber/infinity_drill",
    "industrialforegoing:dissolution_chamber/infinity_hammer",
    "industrialforegoing:dissolution_chamber/infinity_launcher",
    "industrialforegoing:dissolution_chamber/infinity_saw",
    "industrialforegoing:dissolution_chamber/infinity_trident",
    "minecraft:copper_ingot_blast_recycle",
    "minecraft:copper_ingot_smelt_recycle",
    "minecraft:enchanting_table",
    "pneumaticcraft:compressed_iron_block_from_ingot",
    "scguns:advanced_composter",
    "scguns:create/ancient_brass_brass_from_mixing",
    "scguns:create/diamond_steel_blend_from_mixing",
    "scguns:create/diamond_steel_ingot_from_mixing",
    "scguns:create/scorched_blend_from_mixing",
    "scguns:create/treated_brass_blend_from_mixing",
    "scguns:create/treated_brass_ingot_from_mixing",
    "scguns:create/treated_iron_crushing",
    "scguns:gun_bench",
    "scguns:macerator",
    "scguns:macerator/scorched_blend_from_macerating",
    "scguns:macerator/treated_brass_blend_from_brass_mask_from_macerating",
    "scguns:macerator/treated_brass_blend_from_macerating",
    "scguns:mechanical_press",
    "scguns:pebbles_from_gravel",
    "scguns:plasma_block_charging",
    "scguns:plasma_core",
    "scguns:plasma",
    "scguns:powered_macerator/powered_scorched_blend_from_macerating",
    "scguns:powered_macerator/powered_treated_brass_blend_from_brass_mask_from_macerating",
    "scguns:powered_macerator/powered_treated_brass_blend_from_macerating",
    "scguns:treated_brass_ingot_from_blasting_treated_brass_blend",
    "scguns:treated_brass_ingot_from_smelting_treated_brass_blend",
    "scguns:treated_iron/treated_iron_hopper",
    "sophisticatedbackpacks:diamond_backpack",
    "sophisticatedbackpacks:gold_backpack",
    "sophisticatedbackpacks:iron_backpack_from_copper",
    "sophisticatedbackpacks:iron_backpack",
    "sophisticatedbackpacks:netherite_backpack",
  ];
  const removedInputs = [];
  const removedOutputs = [
    '@marbledsarsenal',
    '@marbledsmelees'
  ];

  removedTypes.forEach((type) => event.remove({ type: type }));
  removedIDs.forEach((id) => event.remove({ id: id }));
  removedInputs.forEach((input) => event.remove({ input: input }));
  removedOutputs.forEach((output) => event.remove({ output: output }));
});
